VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes

MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
QMK_SETTINGS = no
CONSOLE_ENABLE = no
TAP_DANCE_ENABLE = no

LTO_ENABLE = yes
